# Site settings
title: Margaret Gilboa
email: mgilboa@mris.com
url: https://mgilboa.github.io
description: "Real Estate Agent based in Langley Forest selling Luxary Properties and Land"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#8A2BE2'

# Footer settings
footer: Margaret Gilboa

#Properties
property1:
  address: 6727 Lucy Lane
  image1:
    title: Front
    location: ../img/properties/lucy/front.JPG
  image2:
    title:
    location:
  image3:
    title:
    location:






# Build settings
markdown: kramdown
permalink: pretty
