# Site settings
title: Margaret Gilboa
email: mgilboa@mris.com
url: https://mgilboa.github.io
description: "Margaret Gilboa is a real estate agent based in Fairfax County, VA"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#8A2BE2'

# Footer settings
footer: Margaret Gilboa

#Properties
property1:
  address1: 6727 Lucy Lane
  address2: McLean, VA 22101






# Build settings
markdown: kramdown
permalink: pretty
